### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Cicero-MF** [IOCare/esp8266GUI#1]
Hi there, 

I know this is 2years old, but I was keen to see what you had done for a GUI redesign.  Unfortunately it doesn't seem to pull the js and css properly, so the site loads without styling.

I ran it in a browser as well and got these errors: 

> jquery.min.js:1 Uncaught SyntaxError: Unexpected token ILLEGAL
> bootstrap.min.js:1 Uncaught SyntaxError: Unexpected token ILLEGAL

**Comment by bkrajendra** [comment]
Hi @Cicero-MF ,
 this is a very old code, i made many changes latter. I'll suggest you to use advanced esp8266 arduino code for a webserver project.
You can use following ESP8266 core for arduino from 

```
https://github.com/esp8266/Arduino
```

Also find this examples for ESP8266 webserver here which can be used directly:

```
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples
```

I hope this is what you looking for and solves your issue.
