### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by edgiru** [IOCare/esp8266GUI#2]
I would like to see a demo of the interface.

**Comment by bkrajendra** [comment]
@edgiru this is very old repo. Recently ESP8266 is working very good through [Arduino core library](https://github.com/esp8266/Arduino).
You can use [this](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser) Example to design ESP 8266 GUI. replace index.html in data folder with nice gui built using Bootstrap or any other UI framework.

I hope this helps.

**Comment by edgiru** [comment]
thanks
